"""Download the site's Google Fonts (latin + latin-ext subsets) into fonts/
and write css/fonts.css with local @font-face rules, so the presentation
renders identically offline. Run from the repo root: python3 tools/fetch_fonts.py
"""
import os
import re
import subprocess
import urllib.parse

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Bricolage+Grotesque:opsz,wght@12..96,500..800"
           "&family=IBM+Plex+Sans:wght@400;500;600"
           "&family=IBM+Plex+Mono:wght@400;500;600"
           "&family=Caveat:wght@500..700&display=swap")
SUBSETS = ("latin", "latin-ext")

# Math and arrow glyphs the text fonts lack (floor brackets, Θ, ≤, ∑, arrows,
# sub/superscript digits). Google Fonts' text= parameter returns a font that
# holds exactly these glyphs, so the whole math fallback is a few KB.
MATH_GLYPHS = ("⌊⌋⌈⌉∑∏≤≥≠≈∈∉∞√∂∫±×÷−·⋅∙∘∗→←↑↓↔⇄⇒⇐⇔↦⟶⟵"
               "ΘΩΣΔΛΠΦΨθλπσωαβγδεμφ∅∀∃∧∨¬⊂⊆∪∩∣‖⟨⟩…"
               "⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻ⁿ₀₁₂₃₄₅₆₇₈₉₊₋ₐₑₙ")


def curl(url, out=None):
    cmd = ["curl", "-sSfL", "--max-time", "60", "-A", UA, url]
    if out:
        subprocess.run(cmd + ["-o", out], check=True)
        return None
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def main():
    css = curl(CSS_URL)
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*{([^}]*)}", css)
    # Variable fonts come back once per requested weight with the same file:
    # merge those into a single rule with a weight range.
    faces = {}
    for subset, body in blocks:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weights = [int(w) for w in re.search(r"font-weight:\s*([\d ]+);", body).group(1).split()]
        style = re.search(r"font-style:\s*(\w+)", body).group(1)
        url = re.search(r"src:\s*url\(([^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()
        face = faces.setdefault((family, subset, url), {"weights": [], "style": style, "urange": urange})
        face["weights"] += weights
    rules = []
    for (family, subset, url), face in faces.items():
        lo, hi = min(face["weights"]), max(face["weights"])
        weight = str(lo) if lo == hi else f"{lo} {hi}"
        style, urange = face["style"], face["urange"]
        slug = re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")
        name = f"{slug}-{weight.replace(' ', '-')}-{subset}.woff2"
        curl(url, os.path.join("fonts", name))
        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url(../fonts/{name}) format('woff2');\n"
            f"  unicode-range: {urange};\n"
            "}\n")
        print("saved", name)
    math_css = curl("https://fonts.googleapis.com/css2?family=Noto+Sans+Math&text="
                    + urllib.parse.quote(MATH_GLYPHS))
    math_url = re.search(r"src:\s*url\(([^)]+)\)", math_css).group(1)
    curl(math_url, os.path.join("fonts", "tc-math.woff2"))
    ranges = ", ".join("U+%04X" % cp for cp in sorted({ord(c) for c in MATH_GLYPHS}))
    rules.append(
        "/* Noto Sans Math, reduced to the glyphs listed in tools/fetch_fonts.py */\n"
        "@font-face {\n"
        "  font-family: 'TC Math';\n"
        "  font-style: normal;\n"
        "  font-weight: 100 900;\n"
        "  font-display: swap;\n"
        "  src: url(../fonts/tc-math.woff2) format('woff2');\n"
        f"  unicode-range: {ranges};\n"
        "}\n")
    print("saved tc-math.woff2")
    with open(os.path.join("css", "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/fetch_fonts.py - vendored Google Fonts "
                 "(SIL Open Font License). */\n" + "\n".join(rules))


if __name__ == "__main__":
    main()
